### ISSUE TITLE
IEMOCAP dataset 

### ISSUE THREAD

**Issue by yuerunyu** [wenliangdai/Multimodal-End2end-Sparse#1]
@wenliangdai @SamuelCahyawijaya Hi , I have sent a request info to sail.usc.edu ,But haven't recevied a response,can you give me a passwd?

**Comment by wenliangdai** [comment]
@yuerunyu Hi there, did you check your junk mailbox? It might be mis-classified. It's better to give you the password after you get their response. Thanks!

**Comment by yuerunyu** [comment]
I have got the dataset,wating for 5 days....close the issue.
