### ISSUE TITLE
Questions about Evaluation

### ISSUE THREAD

**Issue by LingFengGold** [wenliangdai/Multimodal-End2end-Sparse#10]
There are two functions (eval_mosei_emo, eval_iemocap) in the '/utils/evaluate.py'. My question is what is the difference between these two functions, I see that both use weighted accuracy in there, but you have calculated acc and Wacc separately for both iemocap and modei datasets in the paper. In the code you provided, for both datasets, do you use eval_iemocap by default as long as it is BCEloss?

**Comment by LingFengGold** [comment]
I would like to get your answers, thank you very much!

**Comment by wenliangdai** [comment]
Question resolved by email

**Comment by JYeonKim** [comment]
@LingFengGold Hi, I have the same question! Could you tell me the answer that the authors told you by email? I would be very grateful if you could share it. 

If it's difficult to answer in the comments, please contact me via email (juyeonk.kor@gmail.com)

Thank you! :)
