### ISSUE TITLE
accuracy mismatch

### ISSUE THREAD

**Issue by bhavanisambaturu** [wenliangdai/Multimodal-End2end-Sparse#15]
I tried to run the code with the following arguments:

python main.py -lr=5e-5 -ep=40 -mod=tav -bs=8 --img-interval=500 --early-stop=6 --loss=bce --cuda=3 --model=mme2e --num-emotions=6 --trans-dim=64 --trans-nlayers=4 --trans-nheads=4 --text-lr-factor=10 --text-model-size=base --text-max-len=100

The papers says that we get an accuracy of 84.5% but the best accuracy that I am getting is 76.9% on the IEMOCAP dataset. Could you please put the exact arguments to reproduce the results of the paper?

**Comment by wenliangdai** [comment]
Hi, in line 177 of the evaluate.py, the current code uses weighted accuracy for evaluating IEMOCAP, however, it should be the standard accuracy. Could you please try to comment out line 177 and use line 178 to evaluate? I'll change the code later. Thanks

**Comment by bhavanisambaturu** [comment]
Dear author,

I realised it and tried it yesterday. It worked and gave the results given
in the paper.

**Comment by wenliangdai** [comment]
Cool!
