### ISSUE TITLE
CMU-MOSEI raw dataset

### ISSUE THREAD

**Issue by xjtupanda** [wenliangdai/Multimodal-End2end-Sparse#17]
Hello! The link to the raw CMU-MOSEI dataset [http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip](url) is no longer available, could you please share it?

**Comment by Meng98L** [comment]
> Hello! The link to the raw CMU-MOSEI dataset [http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip](url) is no longer available, could you please share it?

Hello, have you got the raw CMU-MOSEI dataset?

**Comment by xjtupanda** [comment]
> > Hello! The link to the raw CMU-MOSEI dataset [http://immortal.multicomp.cs.cmu.edu/raw_datasets/CMU_MOSEI.zip](url) is no longer available, could you please share it?
> 
> Hello, have you got the raw CMU-MOSEI dataset?


@LM-MSA 
The link to [CMU-MultimodalSDK](https://github.com/A2Zadeh/CMU-MultimodalSDK) is no longer available. There are some forks on GitHub, though. I suppose at least for now the dataset is not accessible. Maybe you should contact the original author of the dataset.
