### ISSUE TITLE
Hey , about your processed data.

### ISSUE THREAD

**Issue by SYF111** [wenliangdai/Multimodal-End2end-Sparse#2]
I was trying to run your code. But i have trouble  downloading the preprocessed data. It is so large that I fail to download from your link. Could you please offer other links to download , such as baidu netdisk .  Thanks.

**Comment by wenliangdai** [comment]
@SYF111 
I see, I will upload it to Baidu Cloud later this week.

**Comment by SYF111** [comment]
OK, thanks a lot.   😃 ❤️

**Comment by wenliangdai** [comment]
@SYF111 
Hi, I tried to upload to Baidu Cloud. However, the single file size limit is 20GB. Do you know any other cloud service without this limitation?

Also, I download my data successfully from the OneDrive. If you fail, can you change the computer setup to prevent it from sleeping during the download?

**Comment by SYF111** [comment]
@wenliangdai 
Could you try to use 7z to compress a single big file into small files ？

OneDrive is ok, but maybe my network is not very stable, once its disconnected. I have to restart. Perhaps you can compress a large file into small ones and upload to onedrive. 10G per file would be okay if it's not too much trouble.

**Comment by wenliangdai** [comment]
@SYF111 
Hi, it's very hard to split into small files. Can you set your computer to "do not sleep" and try to download again?
The first time I tried to download from OneDrive also failed due to this issue. After I make my computer not go to sleep, the download succeeds.

**Comment by SYF111** [comment]
I see, will try. Closing the issue now.
