### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by 1054651112** [wenliangdai/Multimodal-End2end-Sparse#3]
Hi，When I was running the code, I encountered an error as follows:
       cls_feature = last_hidden_state[:, 0]
       TypeError: string indices must be integers

I don't know the reason, I‘m looking forward to your answer!
Thank you!

**Comment by wenliangdai** [comment]
Hi, with this limited information, I'm not sure what causes this error. The first thing to check is, what version of transformers library are you using? I use 3.4.0 for this project.

**Comment by 1054651112** [comment]
Thank you very much for your reply. I'll try changing the version of transformers.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wenliangdai/Multimodal-End2end-Sparse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wenliangdai/Multimodal-End2end-Sparse] string indices must be integers (#3)





 
Hi, with this limited information, I'm not sure what causes this error. The first thing to check is, what version of transformers library are you using? I use 3.4.0 for this project.
