### ISSUE TITLE
Can you upload the code that generates *_split.txt?

### ISSUE THREAD

**Issue by FriedaSmith** [wenliangdai/Multimodal-End2end-Sparse#6]
Can you upload the code that generates ***_split.txt**? I have trouble downloading the preprocessed data, so I want to process the raw data directly.

**Comment by wenliangdai** [comment]
Hi, thanks for your interest. I've uploaded the split files to this repo https://github.com/wenliangdai/Multimodal-End2end-Sparse/tree/main/data%20split, please check.
